-- ── Articles table ───────────────────────────────────────────────────────
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  excerpt text not null,
  body text not null,
  date text not null,
  featured boolean not null default false,
  bg text not null default 'linear-gradient(135deg, #04334c 0%, #0a6b6b 100%)',
  img text,
  created_at timestamptz not null default now()
);

alter table public.articles enable row level security;

-- Anyone (including anonymous site visitors) can read articles.
create policy "Public read access" on public.articles
  for select using (true);

-- Only logged-in users (i.e. you, via the admin page) can write.
create policy "Authenticated insert" on public.articles
  for insert to authenticated with check (true);
create policy "Authenticated update" on public.articles
  for update to authenticated using (true) with check (true);
create policy "Authenticated delete" on public.articles
  for delete to authenticated using (true);

insert into public.articles (title, category, excerpt, body, date, featured, bg, img) values ('تمكين الشباب في عصر التحديات', 'الشباب', 'نقاش معمّق حول دور الجيل الجديد في صياغة مستقبل الأمة وتحدياتهم في عالم متسارع التحولات.', 'نقاش معمّق حول دور الجيل الجديد في صياغة مستقبل الأمة وتحدياتهم في عالم متسارع التحولات.

يعيش شباب اليوم في عالم مختلف تمامًا عمّا عاشه الجيل الذي سبقهم؛ عالم يتسم بالتسارع التقني وتقلّب سوق العمل وتعدد مصادر المعرفة. هذا الواقع يفرض عليهم مهارات جديدة لم تكن مطلوبة من قبل، أبرزها القدرة على التعلّم المستمر والتكيّف السريع مع المتغيرات.', '١٠ أبريل ٢٠٢٦', false, 'linear-gradient(135deg, #04334c 0%, #0a6b6b 100%)', '/articles/imgi_10_tim-marshall-WUwKbFL81mw-unsplash-300x200.jpg');
insert into public.articles (title, category, excerpt, body, date, featured, bg, img) values ('قيادة التحول في المؤسسات', 'التحول', 'كيف تقود تحولًا حقيقيًا في بيئة المؤسسات؟ أدوات ومناهج مجربة من تجارب قيادية فعلية.', 'كيف تقود تحولًا حقيقيًا في بيئة المؤسسات؟ أدوات ومناهج مجربة من تجارب قيادية فعلية.

التحول المؤسسي ليس مجرد تغيير في الهيكل التنظيمي أو الأنظمة، بل هو رحلة ثقافية تبدأ من القناعة الداخلية لدى القادة قبل أن تنتقل إلى بقية أفراد المؤسسة.', '٢ أبريل ٢٠٢٦', false, 'linear-gradient(148deg, #04334c 0%, #0c7070 100%)', '/articles/imgi_27_EI-copy-e1717586612304-1024x694.jpg');
insert into public.articles (title, category, excerpt, body, date, featured, bg, img) values ('هل أنت ضيف في المجلس؟', 'القيادة', 'من منّا لم يقابل ذلك الحكيم الصامت الذي يتأمل عميقًا وينصت كثيرًا، ولكنه إذا نطق أبهر السامعين.', 'من منّا لم يقابل ذلك الحكيم الصامت الذي يتأمل عميقًا وينصت كثيرًا، ولكنه إذا نطق أبهر السامعين.

هناك نوعان من الحضور في أي مجلس: من يتكلم كثيرًا ليُشعر الآخرين بحضوره، ومن يصمت طويلًا ليمنح نفسه فرصة الفهم قبل الكلام. النوع الثاني هو من يترك الأثر الحقيقي.', '٢٠ مارس ٢٠٢٦', true, 'linear-gradient(122deg, #04334c 0%, #085f6a 100%)', '/articles/imgi_49_MicrosoftTeams-image-10-1024x768.jpg');
insert into public.articles (title, category, excerpt, body, date, featured, bg, img) values ('فن القيادة الفعّالة', 'القيادة', 'القيادة الحقيقية ليست لقبًا أو منصبًا، بل هي أثر تتركه في قلوب من تقودهم وعقولهم.', 'القيادة الحقيقية ليست لقبًا أو منصبًا، بل هي أثر تتركه في قلوب من تقودهم وعقولهم.

القائد الفعّال لا يُقاس بعدد من يتبعونه، بل بعدد من يصنعهم قادة من بعده. هذا هو الفارق الجوهري بين الإدارة والقيادة.', '١٥ مارس ٢٠٢٦', false, 'linear-gradient(140deg, #04334c 0%, #0b6870 100%)', '/articles/imgi_20_MicrosoftTeams-image-54-768x768.png');
insert into public.articles (title, category, excerpt, body, date, featured, bg, img) values ('ريادة الأعمال في المنطقة', 'ريادة', 'المنطقة تعيش لحظة تاريخية فارقة. رواد الأعمال اليوم يبنون ما سيستفيد منه الجيل القادم.', 'المنطقة تعيش لحظة تاريخية فارقة. رواد الأعمال اليوم يبنون ما سيستفيد منه الجيل القادم.

مع تسارع مبادرات التحول الاقتصادي في المنطقة، أصبحت ريادة الأعمال خيارًا استراتيجيًا وليس مجرد مغامرة فردية، ويتطلب ذلك دعمًا مؤسسيًا حقيقيًا للرواد الشباب.', '٨ مارس ٢٠٢٦', false, 'linear-gradient(130deg, #04334c 0%, #096565 100%)', '/articles/imgi_45_pascal-van-de-vendel-RqjNWnQbWGU-unsplash-1-1024x731.jpg');
insert into public.articles (title, category, excerpt, body, date, featured, bg, img) values ('استراتيجيات النجاح المهني', 'المهنة', 'النجاح المهني لا يأتي بالصدفة، بل هو نتاج قرارات ذكية واستثمار مستمر في النمو الشخصي.', 'النجاح المهني لا يأتي بالصدفة، بل هو نتاج قرارات ذكية واستثمار مستمر في النمو الشخصي.

من أهم القرارات التي يتخذها المحترفون الناجحون هو الاستثمار المستمر في تطوير الذات، حتى في أوقات الاستقرار الظاهري في المسار المهني.', '١ مارس ٢٠٢٦', false, 'linear-gradient(145deg, #04334c 0%, #0a6b6b 100%)', '/articles/imgi_42_WFH.-2-2-1536x1024.jpg');
insert into public.articles (title, category, excerpt, body, date, featured, bg, img) values ('مهارة تحتاجها حتى لو كنت عبقريًا', 'القيادة', 'الذكاء وحده لا يكفي. ثمة مهارة واحدة تجعل الموهبة تُترجم إلى نتائج ملموسة في كل مرحلة.', 'الذكاء وحده لا يكفي. ثمة مهارة واحدة تجعل الموهبة تُترجم إلى نتائج ملموسة في كل مرحلة.

تلك المهارة هي الانضباط الذاتي: القدرة على المتابعة والتنفيذ حتى عندما يغيب الحماس الأولي.', '٢٢ فبراير ٢٠٢٦', false, 'linear-gradient(125deg, #04334c 0%, #0c6e6e 100%)', '/articles/imgi_7_Picture1-1-300x300.png');
insert into public.articles (title, category, excerpt, body, date, featured, bg, img) values ('ماذا يخبرك رمضان عن نفسك؟', 'الإدارة', 'الشهر الكريم مرآة صادقة تكشف عن طبيعتك الحقيقية في إدارة الوقت والطاقة وترتيب الأولويات.', 'الشهر الكريم مرآة صادقة تكشف عن طبيعتك الحقيقية في إدارة الوقت والطاقة وترتيب الأولويات.

كيف نستثمر روتين رمضان اليومي كفرصة لإعادة النظر في عاداتنا وأولوياتنا طوال العام؟', '١٢ فبراير ٢٠٢٦', false, 'linear-gradient(138deg, #04334c 0%, #085e6a 100%)', '/articles/imgi_17_IMG_1724-2-e1711534233915-768x1024.png');
insert into public.articles (title, category, excerpt, body, date, featured, bg, img) values ('مهارة يغفل عنها الكثيرون', 'المهنة', 'مهارة التواصل الفعّال أعمق من مجرد الكلام. تعرّف على البُعد الخفي الذي يُفرق بين المؤثر والمهمَّش.', 'مهارة التواصل الفعّال أعمق من مجرد الكلام. تعرّف على البُعد الخفي الذي يُفرق بين المؤثر والمهمَّش.

الإنصات الفعّال هو ذلك البُعد الخفي؛ فالتواصل الحقيقي يبدأ من فهم الطرف الآخر قبل محاولة إيصال فكرتك إليه.', '3 فبراير ٢٠٢٦', false, 'linear-gradient(142deg, #04334c 0%, #0b6570 100%)', '/articles/imgi_6_IMG_8349-300x199.jpg');

-- ── Storage bucket for article images ───────────────────────────────────
insert into storage.buckets (id, name, public)
values ('article-images', 'article-images', true)
on conflict (id) do nothing;

create policy "Public read article images" on storage.objects
  for select using (bucket_id = 'article-images');
create policy "Authenticated upload article images" on storage.objects
  for insert to authenticated with check (bucket_id = 'article-images');
create policy "Authenticated update article images" on storage.objects
  for update to authenticated using (bucket_id = 'article-images');
create policy "Authenticated delete article images" on storage.objects
  for delete to authenticated using (bucket_id = 'article-images');

-- ── Bilingual support for articles (run once) ───────────────────────────
alter table public.articles add column if not exists title_en text;
alter table public.articles add column if not exists category_en text;
alter table public.articles add column if not exists excerpt_en text;
alter table public.articles add column if not exists body_en text;
alter table public.articles add column if not exists date_en text;

-- ── Page content blocks (bilingual, admin-editable) ─────────────────────
create table if not exists public.page_content (
  id bigint generated by default as identity primary key,
  page text not null,
  section_key text not null,
  content_ar text,
  content_en text,
  updated_at timestamptz not null default now(),
  unique (page, section_key)
);

alter table public.page_content enable row level security;

create policy "Public read page content" on public.page_content
  for select using (true);
create policy "Authenticated insert page content" on public.page_content
  for insert to authenticated with check (true);
create policy "Authenticated update page content" on public.page_content
  for update to authenticated using (true) with check (true);
create policy "Authenticated delete page content" on public.page_content
  for delete to authenticated using (true);

-- Seed: Home page "نبذة عني" (About Me) section
insert into public.page_content (page, section_key, content_ar, content_en) values
  ('home', 'profile_name', 'بدر بن حمود البدر', 'Badr bin Hamoud Al-Badr'),
  ('home', 'profile_title', 'عضو مجلس إدارة · مؤلف · متحدث رئيسي', 'Board Member · Author · Keynote Speaker'),
  ('home', 'profile_bio', 'مهتم بتمكين الشباب وقيادة التحول وريادة الأعمال. أرحب بكم في مدونتي التي أشارككم فيها تجاربي ومحطاتي.', 'Passionate about youth empowerment, leadership transformation, and entrepreneurship. Welcome to my blog, where I share my experiences and milestones.')
on conflict (page, section_key) do nothing;
